#!/bin/sh /etc/rc.common

START=99

start(){
    choice=`cat /root/core.txt`
    case $choice in
        sing)
            sh /root/install-sing-box.sh
        ;;
        
        xray)
            sh /root/install-xray-core.sh
        ;;
    esac
}
